package forms;

public class menu extends javax.swing.JFrame {

  
    public menu() {
        initComponents();
        setResizable(false);
        setTitle("MENU PRINCIPAL");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        CerrarSesion = new javax.swing.JMenuItem();
        MenuProductos = new javax.swing.JMenu();
        RegistrarProducto = new javax.swing.JMenuItem();
        ModificarProducto = new javax.swing.JMenuItem();
        EliminarProducto = new javax.swing.JMenuItem();
        EnlistarProductos = new javax.swing.JMenuItem();
        MenuPedidos = new javax.swing.JMenu();
        CrearCanastadePedidos = new javax.swing.JMenuItem();
        GestionarCanastadePedidos = new javax.swing.JMenuItem();
        MenuComprobante = new javax.swing.JMenu();
        GenerarComprobante = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu7.setText("jMenu7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:/Users/U1/Documents/NetBeansProjects/TrabajoVf2/src/main/java/recursos/2.png"));

        jMenu1.setIcon(new javax.swing.ImageIcon("src/main/java/recursos/folder.png"));
        jMenu1.setText("File");

        CerrarSesion.setIcon(new javax.swing.ImageIcon("src/main/java/recursos/bloquear.png"));
        CerrarSesion.setText("Cerrar Sesion");
        CerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSesionActionPerformed(evt);
            }
        });
        jMenu1.add(CerrarSesion);

        jMenuBar1.add(jMenu1);

        MenuProductos.setIcon(new javax.swing.ImageIcon("src/main/java/recursos/productos.png"));
        MenuProductos.setText("Productos");

        RegistrarProducto.setIcon(new javax.swing.ImageIcon("src/main/java/recursos/add.png"));
        RegistrarProducto.setText("Registrar");
        RegistrarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarProductoActionPerformed(evt);
            }
        });
        MenuProductos.add(RegistrarProducto);

        ModificarProducto.setIcon(new javax.swing.ImageIcon("src/main/java/recursos/edit.png"));
        ModificarProducto.setText("Modificar ");
        ModificarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarProductoActionPerformed(evt);
            }
        });
        MenuProductos.add(ModificarProducto);

        EliminarProducto.setIcon(new javax.swing.ImageIcon("src/main/java/recursos/borrar.png"));
        EliminarProducto.setText("Eliminar");
        EliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarProductoActionPerformed(evt);
            }
        });
        MenuProductos.add(EliminarProducto);

        EnlistarProductos.setIcon(new javax.swing.ImageIcon("src/main/java/recursos/job.png"));
        EnlistarProductos.setText("Enlistar");
        EnlistarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnlistarProductosActionPerformed(evt);
            }
        });
        MenuProductos.add(EnlistarProductos);

        jMenuBar1.add(MenuProductos);

        MenuPedidos.setIcon(new javax.swing.ImageIcon("src/main/java/recursos/hacer-un-pedido.png"));
        MenuPedidos.setText("Pedidos");

        CrearCanastadePedidos.setIcon(new javax.swing.ImageIcon("src/main/java/recursos/bienes.png"));
        CrearCanastadePedidos.setText("Crear Canasta");
        CrearCanastadePedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearCanastadePedidosActionPerformed(evt);
            }
        });
        MenuPedidos.add(CrearCanastadePedidos);

        GestionarCanastadePedidos.setIcon(new javax.swing.ImageIcon("src/main/java/recursos/cubo-3d.png"));
        GestionarCanastadePedidos.setText("Gestion de Canasta");
        GestionarCanastadePedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionarCanastadePedidosActionPerformed(evt);
            }
        });
        MenuPedidos.add(GestionarCanastadePedidos);

        jMenuBar1.add(MenuPedidos);

        MenuComprobante.setIcon(new javax.swing.ImageIcon("src/main/java/recursos/factura.png"));
        MenuComprobante.setText("Comprobantes");

        GenerarComprobante.setIcon(new javax.swing.ImageIcon("src/main/java/recursos/comprobar.png"));
        GenerarComprobante.setText("Generar Comprobante");
        GenerarComprobante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerarComprobanteActionPerformed(evt);
            }
        });
        MenuComprobante.add(GenerarComprobante);

        jMenuBar1.add(MenuComprobante);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EnlistarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnlistarProductosActionPerformed
        // TODO add your handling code here:
        new EnlistarProd().setVisible(true);
    }//GEN-LAST:event_EnlistarProductosActionPerformed

    private void RegistrarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarProductoActionPerformed
        // TODO add your handling code here:  
        new RegProd().setVisible(true);
     
    }//GEN-LAST:event_RegistrarProductoActionPerformed

    private void ModificarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarProductoActionPerformed
        // TODO add your handling code here:
        new ModificarProd().setVisible(true);
        
    }//GEN-LAST:event_ModificarProductoActionPerformed

    private void CerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSesionActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CerrarSesionActionPerformed

    private void EliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarProductoActionPerformed
        // TODO add your handling code here:
        new EliminarProd().setVisible(true);
    }//GEN-LAST:event_EliminarProductoActionPerformed

    private void CrearCanastadePedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearCanastadePedidosActionPerformed
        // TODO add your handling code here:
        new Canasta().setVisible(true);
        
    }//GEN-LAST:event_CrearCanastadePedidosActionPerformed

    private void GenerarComprobanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerarComprobanteActionPerformed
        // TODO add your handling code here:
        
        new Comprobante().setVisible(true);
    }//GEN-LAST:event_GenerarComprobanteActionPerformed

    private void GestionarCanastadePedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionarCanastadePedidosActionPerformed
        // TODO add your handling code here:
        new GestionCanasta().setVisible(true);
    }//GEN-LAST:event_GestionarCanastadePedidosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new menu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CerrarSesion;
    private javax.swing.JMenuItem CrearCanastadePedidos;
    private javax.swing.JMenuItem EliminarProducto;
    private javax.swing.JMenuItem EnlistarProductos;
    private javax.swing.JMenuItem GenerarComprobante;
    private javax.swing.JMenuItem GestionarCanastadePedidos;
    private javax.swing.JMenu MenuComprobante;
    private javax.swing.JMenu MenuPedidos;
    private javax.swing.JMenu MenuProductos;
    private javax.swing.JMenuItem ModificarProducto;
    private javax.swing.JMenuItem RegistrarProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
