package forms;

import clases.Inventario;
import clases.ManejoFileInventario;
import java.io.*;


public class ModificarProd extends javax.swing.JFrame {

 
    public ModificarProd() {
        initComponents();
        setResizable(false);
        setTitle("MODIFICAR PRODUCTO");
        TextArea1.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIdproducto = new javax.swing.JTextField();
        txtNuevodescipcion = new javax.swing.JTextField();
        txtNuevotipo = new javax.swing.JTextField();
        txtNuevopreciounit = new javax.swing.JTextField();
        btnListaToModificar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea1 = new javax.swing.JTextArea();
        btnModificar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnCerrarventana = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Id PRODUCTO: ");

        jLabel2.setText("NUEVA DESCRIPCION: ");

        jLabel3.setText("NUEVO TIPO:");

        jLabel4.setText("NUEVO PRECIO UNITARIO:");

        btnListaToModificar.setIcon(new javax.swing.ImageIcon("src/main/java/recursos/refresh.png"));
        btnListaToModificar.setText("ACTUALIZAR LISTA");
        btnListaToModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaToModificarActionPerformed(evt);
            }
        });

        TextArea1.setColumns(20);
        TextArea1.setRows(5);
        jScrollPane1.setViewportView(TextArea1);

        btnModificar.setIcon(new javax.swing.ImageIcon("src/main/java/recursos/edit.png"));
        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon("src/main/java/recursos/borrar-escrito.png"));
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnCerrarventana.setIcon(new javax.swing.ImageIcon("src/main/java/recursos/exit.png"));
        btnCerrarventana.setText("CERRAR VENTANA");
        btnCerrarventana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarventanaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdproducto)
                            .addComponent(txtNuevodescipcion)
                            .addComponent(txtNuevotipo)
                            .addComponent(txtNuevopreciounit, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnCancelar)
                                .addComponent(btnModificar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(btnCerrarventana))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnListaToModificar)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(btnListaToModificar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnModificar)
                        .addGap(26, 26, 26)
                        .addComponent(btnCancelar)
                        .addGap(27, 27, 27)
                        .addComponent(btnCerrarventana)
                        .addContainerGap(50, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtIdproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtNuevodescipcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtNuevotipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtNuevopreciounit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnListaToModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaToModificarActionPerformed
        // TODO add your handling code here:
           /**
        *Este método carga los datos de un inventario desde un archivo.
        *@param invProductos Objeto de la clase Inventario que contiene la información del inventario de productos.
        *@param TextArea1 TextArea donde se mostrará la información del inventario.
        */
        Inventario invProductos = new Inventario("PRODUCTOS");
//Se crea un objeto File con el nombre del inventario de productos
        File archivo = new File(invProductos.getTipoInventario());
//Si el archivo existe, se procede a cargar los datos del inventario
        if(archivo.exists()){
            //lectura
            invProductos = ManejoFileInventario.leerInventarioDesdeArchivo(invProductos.getTipoInventario(), invProductos);
            TextArea1.setText(invProductos.getRegistroProductos().toString());
        }
        else{//De lo contrario, se muestra un mensaje indicando que no hay inventario de productos registrado
            TextArea1.setText("NO EXISTE LISTA DE PRODUCTOS REGISTRADOS PARA MOSTRAR");
        }
      
        
        
    }//GEN-LAST:event_btnListaToModificarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
           /**
         * Actualiza un elemento del inventario con la información ingresada en los campos de texto
         * Si el archivo del inventario existe, se actualiza el elemento correspondiente y se guardan los cambios en el archivo
         * Si el archivo no existe, muestra un mensaje indicando que no existe registro de lista para mostrar
         * Si el precio unitario ingresado no es un número válido, muestra un mensaje indicando que el número es inválido.
         *
         * @param invProductos el inventario de productos a actualizar.
         * @param archivo el archivo que contiene el inventario de productos.
         * @param descipcion la nueva descripción del producto.
         * @param tipo el nuevo tipo del producto.
         * @param precioUnit el nuevo precio unitario del producto.
         * @param id el ID del producto a actualizar.
         * @param esNumero un indicador booleano que especifica si el precio unitario ingresado es un número válido.
         * @param contieneSoloNumeros un indicador booleano que especifica si el ID del producto contiene sólo números.
         */
        Inventario invProductos = new Inventario("PRODUCTOS");
        File archivo = new File(invProductos.getTipoInventario());
        
        String descipcion = txtNuevodescipcion.getText();
        String tipo       = txtNuevotipo.getText();
        String precioUnit = txtNuevopreciounit.getText();
        String id = txtIdproducto.getText();
        
        
        boolean esNumero = txtNuevopreciounit.getText().matches("^\\d+(\\.\\d{2})?$");
        boolean contieneSoloNumeros = txtIdproducto.getText().matches("[0-9]+");
        
       
        if(esNumero&&contieneSoloNumeros){
                jLabel5.setText("");
                int idp = Integer.parseInt(id);
                double precioUni  = Double.parseDouble(precioUnit);


            if(archivo.exists()){
                invProductos = ManejoFileInventario.leerInventarioDesdeArchivo(invProductos.getTipoInventario(), invProductos);
                invProductos.modificarElemento(idp, descipcion, tipo, precioUni);
                ManejoFileInventario.escribirInventarioEnArchivo(invProductos.getTipoInventario(), invProductos);
                txtIdproducto.setText("");
                txtNuevodescipcion.setText("");
                txtNuevopreciounit.setText("");
                txtNuevotipo.setText("");
            }
            else{
                TextArea1.setText("NO EXISTE REGISTRO DE LISTA PARA MOSTRAR");
                txtIdproducto.setText("");
                txtNuevodescipcion.setText("");
                txtNuevopreciounit.setText("");
                txtNuevotipo.setText("");
            }

        }else{
            jLabel5.setText("Numero Invalido");
        }
         
 
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        txtIdproducto.setText("");
        txtNuevodescipcion.setText("");
        txtNuevopreciounit.setText("");
        txtNuevotipo.setText("");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCerrarventanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarventanaActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnCerrarventanaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ModificarProd().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TextArea1;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCerrarventana;
    private javax.swing.JButton btnListaToModificar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtIdproducto;
    private javax.swing.JTextField txtNuevodescipcion;
    private javax.swing.JTextField txtNuevopreciounit;
    private javax.swing.JTextField txtNuevotipo;
    // End of variables declaration//GEN-END:variables
}
